config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get "home/index"
  resources :home, only: :index
  resources :deposits, only: [:new, :create]
  
  resources :accounts, except: [ :create, :new ] do
    resources :deposits, only: [:new, :create]
    resources :withdrawals, only: [:new, :create]
    resources :transfers, only: [:new, :create]
    resources :search, only: [:index]
  end

  root :to => "home#index"
end

app/models/account.rb
class Account < ApplicationRecord
  before_create :assign_unique_account_number
  belongs_to :user
  has_many :deposits
  has_many :withdrawals
  has_many :transfers
  
  validates :account_number, presence: true, if: -> { account_number.present? }
  validates :account_number, uniqueness: true, if: -> { account_number.present? }
  validates_numericality_of :balance, :greater_than_or_equal_to => 0.0
  
  private

  ACCOUNT_NUMBER_RANGE = (10_000..99_999)

  def assign_unique_account_number
    self.account_number = loop do
      number = rand(ACCOUNT_NUMBER_RANGE)
      break number unless Account.exists?(account_number: number)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :account

  validates_numericality_of :value, :greater_than_or_equal_to => 0.0
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :account
  has_one :transfer_rate

  validates_numericality_of :value, :greater_than_or_equal_to => 0.0
end

app/models/transfer_rate.rb
class TransferRate < ApplicationRecord
  belongs_to :transfer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,  and :omniauthable
  after_create :set_account
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
         
  has_one :account
  #has_many :deposits, through: :account
  #has_many :withdrawals, through: :account
  #has_many :transfers, through: :account

  def set_account
    Account.create(user_id: self.id)
  end
end

app/models/withdrawal.rb
class Withdrawal < ApplicationRecord
  belongs_to :account
  
  validates_numericality_of :value, :greater_than_or_equal_to => 0.0
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
 

  # GET /accounts/1
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # def create
  #   @account = Account.new(account_params)

  #   respond_to do |format|
  #     if @account.save
  #       format.html { redirect_to @account, notice: 'Account was successfully created.' }
  #       format.json { render :show, status: :created, location: @account }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @account.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Conta Autalizada!' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.update(status: false)
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Conta Encerrada.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      #@account = Account.find(params[:id])
      @account = current_user.account
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.fetch(:account, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :set_account

  # GET /deposits/new
  def new
    @deposit = Deposit.new
  end

  # POST /deposits
  def create
    destiny_account = Account.find_by(account_number: params[:deposit][:account])
    deposit = Deposit.new(deposit_params.merge(account_id: destiny_account.id))
    @deposit = Operations::Deposit.call(@account,deposit)  
 
    respond_to do |format|
      if @deposit
        
        format.html { redirect_to account_path(@account),
                    notice: 'Depósito Realizado Com Sucesso!' } if current_user.present?
        format.html { redirect_to home_index_path,
        notice: 'Depósito Realizado Com Sucesso!' }
      else
        format.html { render :new }
      end
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = nil
      @account = Account.find(params[:account_id]) if params[:account_id].present?

    end

    # Only allow a list of trusted parameters through.
    def deposit_params
      params.require(:deposit).permit(:value, :account_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to account_path(current_user.account) if current_user
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:first_date].present?
      @first_date = Time.zone.parse(params[:first_date]).beginning_of_day
      @last_date = Time.zone.parse(params[:last_date]).end_of_day
      
      if @last_date.present? && @last_date.present?
        date_range = @first_date..@last_date
        @extract_deposits = current_user.account.deposits.where(created_at: date_range)
        @extract_transfers = current_user.account.transfers.where(created_at: date_range)
        @extract_withdrawals = current_user.account.withdrawals.where(created_at: date_range)

        # @extract_deposit = Account.includes(:withdrawals, :deposits, :transfers)
        #                   .joins(:withdrawals, :deposits, :transfers)
        #                   .where(id: current_user.account.id)
        #                   .where(deposits: { created_at: date_range })  
        #           binding.pry
      end
    end
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_account

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # POST /transfers
  def create
    destiny_account = Account.find_by(account_number: params[:transfer][:account])
    transfer = Transfer.new(transfer_params.merge(account: destiny_account))
    rate = Operations::TransferRateService.call(transfer.value)
    @transfer = Operations::Transfer.call(@account,transfer, rate)  
 
    respond_to do |format|
      if @transfer
        format.html { redirect_to account_path(@account), notice: 'Transferência Realizada Com Sucesso!' }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:account_id])
    end

    # Only allow a list of trusted parameters through.
    def transfer_params
      params.require(:transfer).permit(:value, :account)
    end
end

app/controllers/withdrawals_controller.rb
class WithdrawalsController < ApplicationController
  before_action :set_account

  # GET /withdrawals
  # GET /withdrawals/new
  def new
    @withdrawal = Withdrawal.new
  end

  # POST /withdrawals
  def create
    withdrawal = Withdrawal.new(withdrawal_params)
    @withdrawal = Operations::Withdrawal.call(@account,withdrawal)
 
    respond_to do |format|
      if @withdrawal
        format.html { redirect_to account_path(@account), notice: 'Saque Realizado Com Sucesso!' }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:account_id])
    end

    # Only allow a list of trusted parameters through.
    def withdrawal_params
      params.require(:withdrawal).permit(:value).merge(account_id: @account.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    current_page?(test_path) ? "is-active" : ""
  end
  def formated_date(date)
    date.strftime("%d/%m/%Y as %H:%M")  
  end
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
          
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing conta</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @daccount %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<section class="hero is-info welcome is-small">
<div class="hero-body">
    <div class="container">
        <h3 class="title">
            Olá, <%= current_user.email %> <br/> Seja bem vindo ao NoBank.
        </h3>
        <h2 class="subtitle">
            Agora Vocẽ pode usar seu banco com todas as funcionalidades
        </h2>
    </div>
</div>
</section>
<section class="info-tiles">
  <div class="tile is-ancestor has-text-centered">
      <div class="tile is-parent">
          <article class="tile is-child box">
              <p class="title"><%= @account.balance %></p>
              <p class="subtitle">Saldo</p>
          </article>
      </div>
  </div>
</section>

app/views/deposits/_form.html.erb
<%= form_with(model: [@account, @deposit], local: true) do |f| %>
  <% if deposit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deposit.errors.count, "error") %> prohibited this deposit from being saved:</h2>

      <ul>
        <% deposit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        
      </ul>
    </div>
  <% end %>
  <div class="field">
    <label class="label">Numero da Conta</label>
    <div class="control">
      <%= f.text_field :account, class: 'input', placeholder: "Digite Numero da Conta" %>
    </div>
  </div>
  <div class="field">
    <label class="label">Valor Depositado</label>
    <div class="control">
      <%= f.number_field :value, step: :any, min: 1, class: 'input' %>
    </div>
  </div>
  <div class="control">
    <%= f.submit 'Depositar', class: "button is-primary"  %>
  </div>
<% end %>

app/views/deposits/new.html.erb
<p class="title is-3">Novo Depósito</p>

<%= render 'form', deposit: @deposit %>

app/views/home/index.html.erb
<section class="hero is-info welcome is-small">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                Olá, Seja bem vindo ao NoBank.
            </h1>
            <h2 class="subtitle">
                Para Mais funcionalidades faça seu login
            </h2>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nobank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- START NAV -->
      <%= render partial: "layouts/partials/nav" %>
    <!-- END NAV -->
    <div class="container">
      <div class="columns">
        <%= render partial: "layouts/partials/main_menu" %>
        <div class="column is-9">
            <nav class="breadcrumb" aria-label="breadcrumbs">
              <p id="notice"><%= notice %></p>
            </nav>    
            <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nobank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body>
	<!-- START NAV -->
	<nav class="navbar is-link">
		<div class="container">
			<div class="navbar-brand">
				<a class="navbar-item" href="../">
					Nobank
				</a>
				<span class="navbar-burger burger" data-target="navbarMenu">
					<span></span>
					<span></span>
					<span></span>
				</span>
			</div>
			<div id="navbarMenu" class="navbar-menu">
				<div class="navbar-end">
				</div>
			</div>
		</div>
	</nav>
	<!-- END NAV -->    
	<section class="hero is-fullheight">
		<div class="hero-body">
			<div class="container has-text-centered">
				<div class="columns is-8 is-variable ">
					<div class="column is-two-thirds has-text-left">
						<h1 class="title is-1">Bem Vindo</h1>
						<p class="is-size-4">Seja bem vindo ao Nobank, espero que goste dos nosso serviços</p>
						<div class="social-media">
							<a href="https://facebook.com" target="_blank" class="button is-light is-large"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
							<a href="https://instagram.com" target="_blank" class="button is-light is-large"><i class="fa fa-instagram" aria-hidden="true"></i></a>
							<a href="https://twitter.com" target="_blank" class="button is-light is-large"><i class="fa fa-twitter" aria-hidden="true"></i></a>
						</div>
					</div>
					<div class="column is-one-third has-text-left">
            <%= yield %>
					</div>
				</div>
			</div>
		</div>
	</section>
</body>
</html>

app/views/layouts/partials/_main_menu.html.erb
<div class="column is-3 ">
  
  <aside class="menu is-hidden-mobile">
      <p class="menu-label">
      </p>
      <ul class="menu-list">
        <% unless current_user %>
          <li >
            <a href="<%= home_index_path %>" 
               class="<%= current_class?(home_index_path) %> is-link">
            Inicio
            </a>
          </li>
          <li >
            <a href="<%= new_deposit_path %>" 
              class="<%= current_class?(new_deposit_path) %> is-link">
            Depósito
            </a>
          </li>
          <li style="padding-bottom: 10px;">
            <%= link_to('Acessar Conta', new_user_session_path) %>
          </li>
        <% end %>
      </ul>
      <% if current_user %>
        <p class="menu-label">
            Conta <%= current_user.account.account_number %>
        </p>
        <ul class="menu-list">
        <li >
          <a href="<%= new_account_deposit_path(current_user.account) %>" 
            class="<%= current_class?(new_account_deposit_path(current_user.account)) %> is-link">
          Depósito
          </a>
        </li>
        <li>
          <a href="<%= account_path(current_user.account) %>" 
            class="<%= current_class?(account_path(current_user.account)) %> is-link">
            Saldo
          </a>
        </li>
          <li >
            <a href="<%= account_search_index_path(current_user.account) %>" 
              class="<%= current_class?(account_search_index_path(current_user.account)) %> is-link">
              Extrato
            </a>
          </li>
        

          <li >
            <a href="<%= new_account_withdrawal_path(current_user.account) %>" 
              class="<%= current_class?(new_account_withdrawal_path(current_user.account)) %> is-link">
              Saque
            </a>
          </li>
        
          <li>
            <li >
              <a href="<%= new_account_transfer_path(current_user.account) %>" 
                class="<%= current_class?(new_account_transfer_path(current_user.account)) %> is-link">
                  Tranferências
              </a>
            </li>
          </li>
          <li>
            <a>Encerrar Conta</a>
          </li>
          <li>
            <%= link_to('Sair', destroy_user_session_path, method: :delete) %>
          </li>
        </ul>
      <% end %>
  </aside>
</div>

app/views/layouts/partials/_nav.html.erb
<nav class="navbar is-link">
  <div class="container">
      <div class="navbar-brand">
          <a class="navbar-item brand-text" href="../index.html"> NoBank </a>
          <div class="navbar-burger burger" data-target="navMenu">
            <span></span>
            <span></span>
            <span></span>
            <span></span>  
          </div>
      </div>
      <div id="navMenu" class="navbar-menu">
        <div class="navbar-end">
        <% if current_user %>
          <a class="navbar-item" href="admin.html">
             Agencia: <%= current_user.account.agency %>
          </a>
          <a class="navbar-item" href="admin.html">
             Conta: <%= current_user.account.account_number %>
          </a>
          <% end %>
        </div>
      </div>
  </div>
</nav>

app/views/search/_extract_deposits.html.erb
<div class="card events-card">
  <header class="card-header">
    <p class="card-header-title">
        Depósitos Efetuados
    </p>
    <a href="#" class="card-header-icon" aria-label="more options">
    <span class="icon">
    <i class="fa fa-angle-down" aria-hidden="true"></i>
    </span>
    </a>
  </header>
  <div class="card-table">
      <div class="content">
          <table class="table is-fullwidth is-striped">
              <tbody>
                <% @extract_deposits.each do |extract_deposit| %>
                  <tr>
                    <td width="5%"><i class="fa fa-bell-o"></i></td>
                    <td><%= formated_date(extract_deposit.created_at) %></td>
                    <td>Depósito Efetuado</td>
                    <td class="level-right"><a class="button is-small is-primary" href="#">Valor: <%= extract_deposit.value %></a></td>
                  </tr>
                <% end %>
            </tbody>
          </table>
      </div>
  </div>
</div>

app/views/search/_extract_form.html.erb
<%= form_tag(account_search_index_path(current_user.account), method: :get) do %>
  <div class="field">
    <label class="label">Data Inicial</label>
    <div class="control">
      <%= date_field_tag :first_date, class: 'input' %>
    </div>
  </div>
  <div class="field">
    <label class="label">Data Final</label>
    <div class="control">
      <%= date_field_tag :last_date, class: 'input' %>
    </div>
  </div>
  
  <div class="control">
    <%= submit_tag 'Pesquisar', class: "button is-primary"  %>
  </div>
  <br/>
<% end %>

app/views/search/_extract_transfer.html.erb
<div class="card events-card">
  <header class="card-header">
    <p class="card-header-title">
        Transferências Efetuadas
    </p>
    <a href="#" class="card-header-icon" aria-label="more options">
    <span class="icon">
    <i class="fa fa-angle-down" aria-hidden="true"></i>
    </span>
    </a>
  </header>
  <div class="card-table">
      <div class="content">
          <table class="table is-fullwidth is-striped">
              <tbody>
                <% @extract_transfers.each do |extract_transfer| %>
                  <tr>
                    <td width="5%"><i class="fa fa-bell-o"></i></td>
                    <td><%= formated_date(extract_transfer.created_at) %></td>
                    <td>Transferência Efetuada</td>
                    <td class="level-right"><a class="button is-small is-primary" href="#">Valor: <%= extract_transfer.value %></a></td>
                  </tr>
                <% end %>
            </tbody>
          </table>
      </div>
  </div>
</div>

app/views/search/_extract_withdrawals.html.erb
<div class="card events-card">
  <header class="card-header">
    <p class="card-header-title">
        Saque Efetuados
    </p>
    <a href="#" class="card-header-icon" aria-label="more options">
    <span class="icon">
    <i class="fa fa-angle-down" aria-hidden="true"></i>
    </span>
    </a>
  </header>
  <div class="card-table">
      <div class="content">
          <table class="table is-fullwidth is-striped">
              <tbody>
                <% @extract_withdrawals.each do |extract_withdrawal| %>
                  <tr>
                    <td width="5%"><i class="fa fa-bell-o"></i></td>
                    <td><%= formated_date(extract_withdrawal.created_at) %></td>
                    <td>Saque Efetuado</td>
                    <td class="level-right"><a class="button is-small is-primary" href="#">Valor: <%= extract_withdrawal.value %></a></td>
                  </tr>
                <% end %>
            </tbody>
          </table>
      </div>
  </div>
</div>

app/views/search/index.html.erb
<p class="title is-3">Solicitar Extrato</p>

<%= render 'extract_form' %>

<% if @extract_deposits %>
  <%= render 'extract_deposits' %>
<% end %> 

<% if @extract_withdrawals %>
  <%= render 'extract_withdrawals' %>
<% end %> 

<% if @extract_transfers %>
  <%= render 'extract_transfer' %>
<% end %> 

app/views/transfers/_form.html.erb
<%= form_with(model: [@account, transfer], local: true) do |f| %>
  <% if transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
        <% transfer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div >
  <div class="field">
    <label class="label">Numero da Conta</label>
    <div class="control">
      <%= f.text_field :account, class: 'input', placeholder: "Digite Numero da Conta" %>
    </div>
  </div>
  <div class="field">
    <label class="label">Valor Transferido</label>
    <div class="control">
      <%= f.number_field :value, step: :any, min: 1, class: 'input' %>
    </div>
  </div>
  <div class="control">
    <%= f.submit 'Efetuar Transferência', class: "button is-primary"  %>
  </div>
<% end %>

app/views/transfers/new.html.erb
<p class="title is-3">Nova Trasnferência</p>

<%= render 'form', transfer: @transfer %>

app/views/withdrawals/_form.html.erb
<%= form_with(model: [@account, @withdrawal], local: true) do |f| %>
  <% if withdrawal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(withdrawal.errors.count, "error") %> prohibited this withdrawal from being saved:</h2>

      <ul>
        <% withdrawal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <label class="label">Valor do Saque</label>
    <div class="control">
      <%= f.number_field :value, step: :any, min: 1, class: 'input' %>
    </div>
  </div>

  <div class="control">
    <%= f.submit 'Efetuar Saque', class: "button is-primary"  %>
  </div>
<% end %>

app/views/withdrawals/new.html.erb
<p class="title is-3">Realizar Saque</p>

<%= render 'form', withdrawal: @withdrawal %>